django_application/urls.py
from django import views
from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static
app_name = 'django_application'

urlpatterns = [
    path('home/',views.home, name='home'),
    path('base/',views.base, name='base'),
    path('carlist/',views.carlist, name='carlist'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('findcar/',views.findcar, name='findcar'),
    path('signup/',views.signup, name = 'signup'),
    path('login/',views.login, name = 'login'),
    path('logout/',views.logout, name = 'logout'),
    path('buycardetail/<int:id>',views.buycardetail, name = 'buycardetail'),
    path('cardetail/<int:id>',views.cardetail, name = 'cardetail'),
    path('buycar/<int:id>',views.buycar, name = 'buycar'),
    path('success/',views.success, name = 'success'),
    path('carstatus/',views.carstatus, name = 'carstatus'),
    path('carimage/',views.carimage, name = 'carimage'),

]

django_project/urls.py
from django.contrib import admin
from django.urls import include,path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django_application/',include('django_application.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_application/models.py
from distutils.command.upload import upload
from pyexpat import model
from tkinter import CASCADE
from typing_extensions import Self
from unittest.util import _MAX_LENGTH
from wsgiref.validate import validator
import os
from django.db import models
from djmoney.models.fields import MoneyField
from djmoney.models.validators import MaxMoneyValidator,MinMoneyValidator
from moneyed import USD
from djmoney.money import Money
from django.contrib.auth.models import AbstractUser
from .manager import UserManager
from django.utils.translation import gettext_lazy as _
from django.core.files.storage import FileSystemStorage
from django_google_maps import fields as map_fields

condition_choices = (
    ('poor','poor'),
    ('fair','fair'),
    ('good','good'),
    ('excellent','excellent')
)
car_status = (
    ('available','available'),
    ('sold','sold'),
)

def get_image_path(instance,filename):
    return os.path.join('car',str(instance.Car.id),filename)

class Car(models.Model):
    seller_name = models.CharField(max_length=100)
    seller_mobile = models.CharField(max_length=10)
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    image = models.FileField(null=True,upload_to="car/")
    year = models.DateField()
    condition = models.CharField(max_length=20, choices=condition_choices)
    asking_price = MoneyField(max_digits=10,decimal_places=2,default_currency='USD',
    validators=[MinMoneyValidator(Money(1000,'USD')),MaxMoneyValidator(Money(100000,'USD'))])
    status = models.CharField(max_length=20,choices = car_status,null=True)
    User = models.ForeignKey('User',on_delete=models.CASCADE,null=True)

    def __str__(self):    
        return self.seller_name,

class  BuyCar(models.Model):
    Car = models.ForeignKey(Car,on_delete=models.CASCADE,null=True)   
    buyer_name = models.CharField(max_length=50)
    buyer_number = models.CharField(max_length=10)
    commission = MoneyField(max_digits=10,decimal_places=2,default_currency='USD',default=0)
    net_amount = MoneyField(max_digits=10,decimal_places=2,default_currency='USD',default=0) 
    User = models.ForeignKey('User',on_delete=models.CASCADE,null=True)
        
    def _str_(self):
        return self.buyer_name

    @property
    def commission(self):
        commission = (self.Car.asking_price * 5) /100  
        return commission  

    @property
    def net_amount(self):
        commission = (self.Car.asking_price * 5) /100       
        net_amount = (self.Car.asking_price) - commission 
        return net_amount    

class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'),max_length=50,unique=True)
    phone_no = models.CharField(max_length=10)
    address = map_fields.AddressField(max_length=200,null=True)
    geolocation = map_fields.GeoLocationField(max_length=100,null=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS =  []
    objects = UserManager()

class CarImage(models.Model):
    Car = models.ForeignKey(Car,on_delete=models.CASCADE,null=True) 
    image = models.FileField(upload_to=get_image_path)



    

django_application/forms.py
from django import forms
from django.forms import ModelForm
from .models import Car, User,BuyCar
from django.contrib.auth.forms import UserCreationForm

class DateInput(forms.DateInput):
    input_type =  'date'

class CarForm(ModelForm):
    class Meta:
        model = Car
        fields = ["seller_name","seller_mobile","make","model","image","year","condition","asking_price"]  
        widgets = {
            'year' : DateInput(),
            'image': forms.ClearableFileInput(attrs={'multiple': True}),
        } 
class UserForm(UserCreationForm):
    email = forms.EmailField(label='Email', required=True)

    class Meta:
        model = User
        fields = ("email", "password1", "password2", "phone_no")       

class BuyForm(ModelForm):
    class Meta:
        model = BuyCar   
        fields = ("buyer_name","buyer_number")                                                                                                                                                                                                                                                                                                                                           

django_application/views.py
from multiprocessing import context
import pdb
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.contrib import messages
from .models import Car,BuyCar,User,CarImage
from .forms import CarForm,UserForm,BuyForm
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as django_login
from django.contrib.auth import logout as django_logout
from django.conf import settings
from django.core.mail import send_mail
from django.core .mail import EmailMultiAlternatives
from django.template.loader import render_to_string

def home(request):
    return render(request,'home.html')
def base(request):
    return render(request,'base.html') 
def thankyou(request):
    return render(request,'thankyou.html') 
def success(request):
    return render(request,"success.html")

def carlist(request):     
    form = CarForm 
    if 'save' in request.POST :
        data = CarForm(request.POST, request.FILES)
        images = request.FILES.getlist('image')
        print(data,"----")
        if data.is_valid():
            Car = data.save()
            for i in images:
                CarImage(Car=Car,image=i).save()
              
            return redirect('django_application:thankyou')
    return render(request,'carlist.html',{'form':form})   

def findcar(request):     
    data = Car.objects.all().order_by('-id')
    searchdata = request.GET.get('search')
    if searchdata is not None:  
        data = data.filter(Q(make__icontains = searchdata) | Q(year__icontains = searchdata)).distinct()                       
    paginator = Paginator(data,5) 
    page_number = request.GET.get('page')
    data = paginator.get_page(page_number)
    context = {
        'data' : data
    }
    return render(request,'findcar.html',context)

def signup(request):
    if request.method == 'POST':
        form  = UserForm(request.POST, request.FILES)
        if form.is_valid():    
            form.save()  
            messages.success(request,"successfully Registered !!!")  
            return redirect("django_application:login")
        else:
            return render(request,"signup.html",{'form':form})  
    else:
        form = UserForm(request.POST)
        return render(request,"signup.html",{'form':form}) 

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                django_login(request,user)
                messages.success(request,"Successfully login to Home page !!")
                return redirect('django_application:home')
            else:
                messages.error(request, "Invalid username or password.")
                return redirect('django_application:login')
        else:
            messages.error(request, "Invalid username or password.")
            return redirect('django_application:login')
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})  

def logout(request):
    django_logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect('django_application:base')


def buycardetail(request,id):
    data = Car.objects.filter(id=id).first()
    data1 = CarImage.objects.all() 
    context = {
        'data' : data,
        'id' : id,
        'data1':data1,
    } 
    return render(request,"buycardetail.html",context)  
    
def cardetail(request,id):
        data = Car.objects.filter(id=id).first()    
        context = {
            'data': data,    
            'id': id,
        }    
        return render(request, "cardetail.html", context)
          
def buycar(request,id):
    cardata = Car.objects.get(id=id)
  
    # if cardata.status != 'sold':
    if request.method == 'POST':
            form = BuyForm(request.POST,request.FILES)
            if form.is_valid():
                buyername = form.cleaned_data.get('buyer_name')
                print(buyername,"----")
                buyernumber = form.cleaned_data.get('buyer_number')
                print(buyernumber,"////")   
                buycarobj = BuyCar(Car=cardata,buyer_name= buyername,buyer_number=buyernumber)
                buycarobj.save()    
                return redirect("django_application:success")
            else:    
                return render(request,"buycar.html",{'form':form,'cardata':cardata})   
    cardata.status = 'sold'
    cardata.save()
    form = BuyForm(request.POST)
    return render(request,"buycar.html",{'form':form,'cardata':cardata}) 

def carstatus(request):   
    context = {}
    if request.user.is_superuser: 
        cardata = Car.objects.filter(status = 'sold') 
        context = {
            'cardata': cardata,
        }
    elif request.user.is_authenticated:
        cardata = Car.objects.exclude(status = 'sold')
        context = {
            'cardata': cardata,
        } 
    
    return render(request,'carstatus.html',context)

def carimage(request):
    data = Car.objects.exclude(status='sold')
    context = {
        'data':data,
        'id':id,
    }
    return render(request,'carimage.html',context)    


 

   
    
            
                                              

                    






    
     
    
        

django_application/templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
  <body>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button onclick="history.back()" style="font-size: 15px;">Go Back</button>
    {% if request.user.is_authenticated %}

      <button><a href="{% url 'django_application:logout'%}" style="font-size: 15px;">Logout </a></button>

    {% else %}

      <button><a href="{% url 'django_application:signup'%}" style="font-size: 15px;">Signup</a></button>
      <button><a href="{% url 'django_application:login'%}" style="font-size: 15px;">Login </a></button>
      
    {% endif %}  
    {% if request.user.is_authenticated %}
      {{ request.user }}
    {% endif %}
    
    <br>
        <div class="col-8">
          <h1 class="mt-2"> Car Application</h1>
          <hr class="mt-0 mb-4">
          {% block content %}    
          {% endblock %}
        </div>
  </body>
</html>  
<br>




 

django_application/templates/buycar.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <body>
            <form action="" method="POST" enctype="multipart/form-data">
                <fieldset>
                    <legend>BuyCar Form</legend>
                    {% csrf_token %}
                    <table>
                        {% for form in form %}
                        <tr><td>{{form.label_tag}}</td><td>{{ form }}</td></tr>
                        {% endfor %}
                    </table>
                    <input type="submit" value="Submit" name="save" />
                </fieldset>
            </form>
        </body>
    </head>
</html>
{% endblock %}

django_application/templates/buycardetail.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
 <head>
  </head> 
    <body>
      <table border="1" style="width: 30%;">
                <!-- {% for y in data1 %}
                {% if data.id == y.Car_id %} 
                <img src="/django_application/media/{{y.image}}">
                {% endif %}
                {% endfor %} -->

                {% for y in data1 %}
                {% if data.id == y.Car_id %} 
                <img src="{{y.image.url}}">
                {% endif %}
                {% endfor %}   
                 
            <form action = '{% url "django_application:buycardetail" id %}' method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table border="1" style="width:60%; text-align: center;" >
                    <tr>    
                    <th>Make</th>   
                    <th>Name</th>    
                    <th>Model</th>
                    <th>Image</th>
                    <th>Year</th>
                    <th>Condition</th>
                    <th>Price</th></tr>
                    <tr>
                    <td><a href="/django_application/cardetail/{{data.id}}" >{{ data.make }}</a></td>  
                    <td>{{data.seller_name }}</td>    
                    <td>{{ data.model }}</td>
                    <td><img style="width: 100px; height: 100px;"
                        src="{{data.image.url}}"></td>    
                    <td>{{ data.year }}</td>
                    <td>{{ data.condition }}</td>
                    <td>{{ data.asking_price }}</td></tr>    
                </table><br>        
            </form>
        </body>
</html>
{% endblock %}

django_application/templates/cardetail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <style>
            table, td, th {
              /* border: 1px solid black; */
              /* text-align: center; */
              padding: 10px;
            }  
            table {
              border-collapse: collapse;
              width: 30%;
            } 
            th {
              height: 40px;
            }
        </style>
        <body><h3>Car Details</title></h3>
            <form action="{% url 'django_application:cardetail' id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>    
                <tr><th>Make  :</th>    
                <td>{{ data.make }}</td></tr>

                <tr><th>Name   : </th>
                <td>{{ data.seller_name }}</td></tr>

                <tr><th>Image   : </th>
                <td><img style="width: 100px; height: 100px;"
                src="{{data.image.url}}"></td></tr>

                <tr><th>Model :</th>
                <td>{{ data.model }}</td></tr>

                <tr><th>Year   :</th>
                <td>{{ data.year }}</td></tr>
                
                <tr><th>Condition   : </th>
                <td>{{ data.condition}}</td></tr> 
                
                <tr><th>Price   : </th>
                <td>{{ data.asking_price}}</td></tr>    
                
                <tr><th></th>
                <td><button><a href="{% url 'django_application:buycar' id%}">BUY</a></button></td></tr>
              </table> 
            </form>  
        </body>
    </head>
{% endblock %}

django_application/templates/carimage.html
{% extends 'base.html' %}
{% block content %}
<html>
<head>
    <style>
    .column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

/* Display the columns below each other instead of side by side on small screens */
@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
img {
  border: 1px solid #ddd;
  border-radius: 4px;
  padding: 5px;
  width: 150px;
}

img:hover {
  box-shadow: 0 0 4px 2px rgba(0, 140, 186, 0.5);
}
/* Add some shadows to create a card effect */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.6);
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}
</style>
    </head>    
    <body>
      <h3>List of Cars</h3>
      <div> 
          <form action="{% url 'django_application:carimage' %}" method="POST" enctype="multipart/form-data">    
          {% for i in data %}     
          <a target="_blank" href="{{i.image.url}}" >
          <img style="width: 200px; height: 180px;" src="{{i.image.url}}" ></a>  
          {{i.make}}
          <a href="/django_application/buycardetail/{{i.id}}">More info...</a>   
          {% endfor %}  
      </form>
      </div>        
  </body>
</html>

{% endblock %}

django_application/templates/carlist.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
  <head>
    <body>
      <form
        action="{% url 'django_application:carlist' %}"
        method="POST"
        enctype="multipart/form-data">
        <fieldset>
          <legend>Sale Form</legend>
          {% csrf_token %}
          <table>
          {{ form }}
          </table>
          <input type="submit" value="Submit" name="save" />
        </fieldset>
      </form>
    </body>
  </head>
</html>
{% endblock %}

django_application/templates/carstatus.html
{% extends 'base.html' %}
{% block content %}  
<html>
<head>
    <body>
        <h4>Available/Sold Car detail </h4>
        <form action = "{% url 'django_application:carstatus' %}" method="POST">
        <table border="1" style="text-align: center;">
            <tr>
                <th>Seller Name</th>
                <th>Seller Mobile</th>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>Condition</th>
                <th>Price</th>
                </tr>
            {% for x in cardata %}
            <tr>
                <td>{{x.seller_name}}</td>
                <td>{{x.seller_mobile}}</td>
                <td>{{x.make}}</td>
                <td>{{x.model}}</td>
                <td>{{x.year}}</td>
                <td>{{x.condition}}</td>
                <td>{{x.asking_price}}</td>
            </tr>
            {% endfor %} 
        </table>
        <table><tr><td>
        {% if request.user.is_superuser %}
        <button type="submit" value="buy"><a href="{% url 'django_application:carlist' %}">Add</a></button>
        {% endif %}
        </td><td>
        {% if request.user.is_authenticated %}
        <button type="submit" value="make available"><a href="{% url 'django_application:carimage' %}">Make available</a></button>
        </td></tr>
        {% endif %}            
       </form>
    </body>
</head>    
</html>
{% endblock %}

django_application/templates/findcar.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<head>
    <body><h2>List of Cars</h2>
        <form method="get">
            <input type="text" placeholder="filter by" name="search" value="">
            <input type="submit" value="Submit" name="save" />
            <input type="submit" value="Clear Filter" name="save" /><br><br>
            <table border="1">
                <tr>
                <th>Name</th>
                <th>Make</th>
                <th>Model</th>
                <th>Year</th>
                <th>Condition</th>
                <th>Price</th></tr>
                {% for x in data %} 
                <tr>
                <td>{{ x.seller_name }}</td>
                <td>{{ x.make }}</td>
                <td>{{ x.model }}</td>
                <td>{{ x.year }}</td>
                <td>{{ x.condition }}</td>
                <td>{{ x.asking_price }}</td></tr>
                {% endfor %}   
            </table>
            <div class="pagination">
                <span class="step-links">
                    {% if data.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ data.previous_page_number }}">previous</a>
                    {% endif %}            
                    <span class="current">
                        Page {{ data.number }} of {{ data.paginator.num_pages }}.
                    </span>            
                    {% if data.has_next %}
                        <a href="?page={{ data.next_page_number }}">next</a>
                        <a href="?page={{ data.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                    
                </span>
            </div>
        </form>   
    </body>
</head>
{% endblock %}

django_application/templates/home.html
{% extends 'base.html' %}
{% block content %}
<html lang="en">
 <head>
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
    width: 30%;
    margin: auto;
  }
</style>
</head> 
<body>
          <div class="container">
          <br>
          <div id="myCarousel" class="carousel slide" data-ride="carousel"> 
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <img src="../media/car1.jpg">
                <div class="carousel-caption">  
                </div>
              </div>
              <div class="item">
                <img src="../media/car2.jpg" alt="car" width="500" height="400">
                <div class="carousel-caption">      
                </div>
              </div>
              <div class="item">
                <img src="../media/car3.jpg" alt="car" width="500" height="400">
                <div class="carousel-caption">
                </div>
              </div>
              <div class="item">
                <img src="../media/car4.jpg" alt="car" width="500" height="400">
                <div class="carousel-caption">    
                </div>
              </div>
              <div class="item">
                <img src="../media/car2.jpg" alt="car" width="500" height="400">
                <div class="carousel-caption">    
                </div>
              </div>
            </div>
         
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>     
    <button><a href="{% url 'django_application:carlist'  %}">List Car</a></button><br><br> 
    <button><a href="{% url 'django_application:findcar' %}">Find Car</a></button><br><br>
    <button><a href="{% url 'django_application:carimage' %}">BUY</a></button><br><br>
    <button><a href="{% url 'django_application:carstatus' %}">Make Available</a></button>
    </body>
    </html>    
{% endblock %}

django_application/templates/login.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <body>
            <form action="{% url 'django_application:login'%}" method="POST" enctype="multipart/form-data">
                <fieldset>
                    <legend>Login Form</legend>
                    {% csrf_token %}
                    <table>  
                        {{ form.as_table }}
                    </table>
                    <input type="submit" value="Login" />
                    {% if messages %}
                    {% for message in messages %}
                    <h2>{{message}}</h2>
                    {% endfor %}
                    {% endif %}
                </fieldset>
            </form>
            <!-- <form action="" method="post">
                {% csrf_token %}
            <table>
                <tbody>
                    {{form.as_table}}
                </tbody>
            </table>
            <input type="submit" value="Login">
            {% if messages %}
            {% for message in messages %}
             <h2>{{message}}</h2>
            {% endfor %}
            {% endif %}
        </form> -->
        </body>
    </head>
</html>
{% endblock %}

django_application/templates/mail.html
<!DOCTYPE html>
<head>
    <body>
        <table border="1">
            <tr>   
            <th>Buyer Name</th>  
            <th>Buyer Number</th>   
            <th>Seller Name</th>   
            <th>Seller Mobile</th>    
            <th>Make</th>
            <th>Model</th>
            <th>Year</th>
            <th>Condition</th>
            <th>Price</th>
            <th>Commission</th>
            <th>Net Amount</th>
        </tr>           
        <tr>
            <td>{{ buyer_name }}</td>  
            <td>{{ buyer_number }}</td>  
            <td>{{ seller_name }}</td>  
            <td>{{ seller_mobile }}</td> 
            <td>{{ make }}</td>    
            <td>{{ model }}</td>
            <td>{{ year }}</td>
            <td>{{ condition }}</td>
            <td>{{ asking_price }}</td>
            <td>{{ commission }}</td>
            <td>{{ net_amount }}</td>
        </tr> 
        </table><br>
    </body>
</head>

django_application/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <body>
            <form action="{% url 'django_application:signup'%}" method="POST" enctype="multipart/form-data">
                <fieldset>
                    <legend>Signup Form</legend>
                    {% csrf_token %}
                    <table>
                        {% for form in form %}
                        <tr><td>{{form.label_tag}}</td><td>{{ form }}</td></tr>
                        {% endfor %}
                    </table>
                    <input type="submit" value="Submit" name="save" />
                </fieldset>
            </form>
        </body>
    </head>
</html>
{% endblock %}

django_application/templates/success.html
{% extends 'base.html' %}
{% block content %}
    <h2>Success page</h2>

{% endblock %}

django_application/templates/thankyou.html
{% extends 'base.html' %}{% block content %}<br>
    Thank You !!! Your Car is added for Sale <br><br>

{% endblock %}